---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - unzip
    - default-jre
  become: true

- name: Create jmeter src directory
  file:
    path: "{{ jmeter_src_dir }}"
    state: directory
  tags: jmeter_setup

- name: Create jmeter directory
  file:
    path: "{{ jmeter_base_dir }}"
    state: directory
  become: yes
  tags: jmeter_setup

#jmeter
- name: Copy jmeter
  copy:
    src: "{{ jmeter_archive }}"
    dest: "{{ jmeter_src_dir }}/"
  register: jmeter_copied
  tags: jmeter_setup

- name: Extract archive jmeter
  unarchive:
    src: "{{ jmeter_src_dir }}/{{ jmeter_archive }}"
    dest: "{{ jmeter_root_dir }}"
    copy: no
  when: jmeter_copied.changed
  tags: jmeter_setup
  become: yes

- name: Configure jmeter
  template:
    src: jmeter.properties.j2
    dest: "{{ jmeter_base_dir }}/bin/jmeter.properties"
  become: yes

- name: Add jmeter to path
  file:
    src: "{{ jmeter_base_dir }}/bin/{{ item }}"
    path: /usr/local/bin/{{item }}
    state: link
  with_items:
    - jmeter
    - jmeter-server
  become: yes

#jmeter plugins standard
- name: Copy jmeter plugins standard
  copy:
    src: "{{ jmeter_plugins_standard_archive }}"
    dest: "{{ jmeter_src_dir }}/"
  register: jmeter_plugins_standard_copied
  when: jmeter_plugins_standard_enabled
  tags: jmeter_setup

- name: Extract archive jmeter plugins standard
  unarchive:
    src: "{{ jmeter_src_dir }}/{{ jmeter_plugins_standard_archive }}"
    dest: "{{ jmeter_base_dir }}"
    copy: no
#    owner="{{ jmeter_owner }}"
#    group="{{ jmeter_group }}"
  when: jmeter_plugins_standard_copied.changed and jmeter_plugins_standard_enabled
  tags: jmeter_setup
  become: yes

#jmeter plugins extras
- name: Copy jmeter plugins extras
  copy:
    src: "{{ jmeter_plugins_extras_archive }}"
    dest: "{{ jmeter_src_dir }}/"
  register: jmeter_plugins_extras_copied
  when: jmeter_plugins_extras_enabled
  tags: jmeter_setup

- name: Extract archive jmeter plugins extras
  unarchive:
    src: "{{ jmeter_src_dir }}/{{ jmeter_plugins_extras_archive }}"
    dest: "{{ jmeter_base_dir }}"
    copy: no
#    owner="{{ jmeter_owner }}"
#    group="{{ jmeter_group }}"
  when: jmeter_plugins_extras_copied.changed and jmeter_plugins_extras_enabled
  tags: jmeter_setup
  become: yes

#jmeter plugins extraslibs
- name: Copy jmeter plugins extraslibs
  copy:
    src: "{{ jmeter_plugins_extraslibs_archive }}"
    dest: "{{ jmeter_src_dir }}/"
  register: jmeter_plugins_extraslibs_copied
  when: jmeter_plugins_extraslibs_enabled
  tags: jmeter_setup

- name: jmeter | Extract archive jmeter plugins extraslibs
  unarchive:
    src: "{{ jmeter_src_dir }}/{{ jmeter_plugins_extraslibs_archive }}"
    dest: "{{ jmeter_base_dir }}"
    copy: no
#    owner="{{ jmeter_owner }}"
#    group="{{ jmeter_group }}"
  when: jmeter_plugins_extraslibs_copied.changed and jmeter_plugins_extraslibs_enabled
  tags: jmeter_setup
  become: yes

#jmeter serveragent
- name: Create base directory for serveragent
  file:
    dest: "{{ jmeter_serveragent_base_dir }}"
    state: directory
  when: jmeter_serveragent_enabled
  tags: jmeter_setup
  become: yes

- name: Copy jmeter serveragent
  copy:
    src: "{{ jmeter_serveragent_archive }}"
    dest: "{{ jmeter_src_dir }}/"
  register: jmeter_serveragent_copied
  when: jmeter_serveragent_enabled
  tags: jmeter_setup

- name: Extract archive jmeter server agent
  unarchive:
    copy: no
    src: "{{ jmeter_src_dir }}/{{ jmeter_serveragent_archive }}"
    dest: "{{ jmeter_serveragent_base_dir }}"
  # when: jmeter_serveragent_copied.changed
  tags: jmeter_setup
  become: yes

- name: Add jmeter-agent service
  template:
    src: jmeter-agent.service.j2
    dest:  /etc/systemd/system/jmeter-agent.service
    mode: 0777
  when: jmeter_serveragent_enabled
  become: yes

- name: Start the jmeter-agent service
  service:
    name: jmeter-agent
    state: restarted
    enabled: yes
  when: jmeter_serveragent_enabled
  become: yes

- name: Configure jmeter remote_hosts
  lineinfile:
    dest: "{{ jmeter_base_dir }}/bin/jmeter.properties"
    # dest: /usr/local/Cellar/jmeter/3.1/libexec/bin/jmeter.properties
    regexp: ^remote_hosts=.*
    line: remote_hosts={{ groups['tag_Type_indigo_tests'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}
  delegate_to: indigo_tests_controller
  run_once: true
  become: true

- name: Add jmeter-server service
  template:
    src: jmeter-server.service.j2
    dest: /etc/systemd/system/jmeter-server.service
    mode: 0777
  become: yes
  when: inventory_hostname in groups['tag_Type_indigo_tests']

- name: Start the jmeter-server service
  service:
    name: jmeter-server
    state: restarted
    enabled: yes
  become: yes
  when: inventory_hostname in groups['tag_Type_indigo_tests']

# - debug: msg=" jmeter | Start jmeter agent {{jmeter_serveragent_base_dir}}/startAgent.sh"
# - debug: msg=" jmeter | Start jmeter {{jmeter_base_dir}}/{{ jmeter_name }}/bin/jmeter"
