---

- name: Ensure that APT works with the https method
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg-curl

- name: Install docker GPG key
  apt_key: keyserver=https://download.docker.com/linux/ubuntu/gpg id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88 state=present
  tags:
    - docker
    - gpg_key

- name: Add docker apt repository
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" state=present
  tags:
    - docker
    - apt_repository

- name: Update apt-cache
  apt: update_cache=yes
  tags:
    - docker
    - apt_cache

- name: Install docker package
  apt: name=docker-ce state=present
  tags:
    - docker
    - install
