---
- name: Install docker-compose
  become: true
  pip:
    name: docker-compose
    version: "1.9.0"

- name: Add user to docker group
  become: true
  user:
    name: ubuntu
    groups: docker
    append: yes

# Hack that allows the ubuntu user to be actually part of the docker group
- name: Kill SSH
  shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
  async: 3
  poll: 2
