---
# Needed in Ubuntu 16.04 (that bundles python3)
- hosts: all
  gather_facts: no
  become: true
  pre_tasks:
    - name: Install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Create docker group
      group:
        name: docker

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

- hosts: all
  become: true
  roles:
    - ansible-role-hostname
